export const changelog = [
  { version: "0.6.1", title: "Native sync transport & status UX polish", items: ["Routed relay push, pull, test, and device requests through the native Rust HTTP client", "Fixed sync failures caused by WebKitGTK mixed-content blocking on local HTTP relays", "Improved sync status states with READY, SYNCING, and accurate CONNECTED feedback", "Added a background connection test when opening sync settings"], link: "https://github.com/termimus/termimus-ssh/releases/tag/v0.6.1" },
  { version: "0.6.0", title: "Local terminal, biometric auth & UI overhaul", items: ["Added an integrated local terminal / PTY shell for offline command-line work", "Added biometric authentication for master password unlock and quick vault access", "Added themes and workspace improvements across the desktop UI", "Made in-session vault unlock cancellable and manual locking silent", "Fixed macOS fullscreen window controls and sync folder conflict handling"], link: "https://github.com/termimus/termimus-ssh/releases/tag/v0.6.0" },
  { version: "0.5.1", title: "Interactive terminal search & tab bar redesign", items: ["Added Ctrl+F / Cmd+F interactive search in terminal buffers", "Redesigned tab bar spacing, contrast, and middle-click close behavior", "Improved terminal navigation and visual clarity"], link: "https://github.com/termimus/termimus-ssh/releases/tag/v0.5.1" },
  { version: "0.5.0", title: "SSH ProxyJump & custom host controls", items: ["Added bastion / jump host support with SSH ProxyJump", "Redesigned custom select controls across the host management UI", "Improved host connection workflows"], link: "https://github.com/termimus/termimus-ssh/commits/main/?since=2026-09-01&until=2026-10-01" },
  { version: "0.4.8–0.4.9", title: "Faster host management", items: ["Auto-detected Linux distribution icons over SSH", "Added compact host list view and duplicate host actions", "Added throttled ping latency monitoring"], link: "https://github.com/termimus/termimus-ssh/commits/main/?since=2026-08-01&until=2026-09-01" },
  { version: "0.4.7", title: "Lower-latency terminal input", items: ["Enabled TCP_NODELAY for SSH, SFTP, and tunnel connections", "Added adaptive output batching for immediate interactive keystroke echoes", "Reduced terminal typing latency during active sessions"], link: "https://github.com/termimus/termimus-ssh/releases/tag/v0.4.7" },
  { version: "0.4.6", title: "Atomic session split & workspace tabs", items: ["Made split-session opening atomic to prevent intermediate layout states", "Persisted SSH connection progress across component remounts", "Displayed workspace names in cluster session tabs"], link: "https://github.com/termimus/termimus-ssh/releases/tag/v0.4.6" },
  { version: "0.4.5", title: "Clipboard improvements", items: ["Fixed paste from external applications on Linux and WebKitGTK", "Added a safer clipboard-manager path with browser fallback", "Fixed tab row clipping on narrow windows"], link: "https://github.com/termimus/termimus-ssh/releases/tag/v0.4.5" },
  { version: "0.4.3–0.4.4", title: "Support, updates & terminal performance", items: ["Added Ko-fi support links and automatic update checking", "Reduced unnecessary terminal re-renders and batched SSH PTY output", "Improved connection progress and automatic terminal cleanup"], link: "https://github.com/termimus/termimus-ssh/releases/tag/v0.4.4" },
  { version: "0.3.0", title: "E2EE sync overhaul", items: ["Added resilient live sync with WebSocket heartbeat", "Added tombstone deletion propagation and revision retention", "Added connected-device status and atomic vault rekeying"], link: "https://github.com/termimus/termimus-ssh/releases/tag/v0.3.0" },
  { version: "0.2.1", title: "Multi-server workspaces", items: ["Added multi-server workspaces and cluster launching", "Improved settings navigation and select controls", "Modernized the desktop UI with the Obsidian palette"], link: "https://github.com/termimus/termimus-ssh/releases/tag/v0.2.1" },
  { version: "0.1.0–0.1.1", title: "Initial release", items: ["SSH terminal, SFTP, tunnels, snippets, and host groups", "AES-256-GCM vault with Argon2id key derivation", "Self-hosted end-to-end encrypted sync relay"], link: "https://github.com/termimus/termimus-ssh/releases" },
];
